#ifndef PRIVATEDIARYCORE_GLOBAL_H
#define PRIVATEDIARYCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRIVATEDIARYCORE_LIBRARY)
#  define PRIVATEDIARYCORE_EXPORT Q_DECL_EXPORT
#else
#  define PRIVATEDIARYCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // PRIVATEDIARYCORE_GLOBAL_H
